# ~/.config/kitty/kitty.conf

env TERM xterm-kitty

font_family JetBrainsMono Nerd Font
font_size 18.0

map PageUp increase_font_size
map PageDown decrease_font_size

macos_option_as_alt yes
window_title_format

hide_window_decorations yes

background_opacity 0.72
background_blur 10

initial_window_width 110c
initial_window_height 30c

scrollback_lines 100000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
repaint_delay 10
input_delay 3
sync_to_monitor yes
cursor_stop_blinking_after 15.0
shell_integration enabled
close_on_child_death yes


############## MacOS ##############
macos_colorspace default

window_border_width 6
active_border_color #e6e6e6
inactive_border_color #2a2a2a

foreground #f2f2f2
background #141416

selection_foreground #141416
selection_background #d7d7d7

cursor #ffffff
cursor_text_color #141416

background_opacity 0.80

color0  #e3dac9
color8  #64646d

color1  #a3a3ac
color9  #6a6a72

color2  #e3dac9
color10 #767680

color3  #62626b
color11 #888891

color4  #6e6e78
color12 #9a9aa3

color5  #7a7a85
color13 #acacb4

color6  #a3a3ac
color14 #c2c2c9

color7  #d0d0d3
color15 #f4f4f6

############## MacOS ##############

map cmd+p new_tab
map cmd+a previous_tab
map cmd+s next_tab
map cmd+shift+\ close_tab
map shift+enter send_text all \e\r

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map cmd+shift+a move_tab_backward
map cmd+shift+s move_tab_forward
map cmd+shift+r set_tab_title
map cmd+shift+h show_scrollback
map cmd+k combine : clear_terminal scrollback active : send_text normal \x0c

