# ~/.config/kitty/kitty.conf

env TERM xterm-256color

font_family JetBrainsMono Nerd Font
font_size 18.0

map PageUp increase_font_size
map PageDown decrease_font_size

window_title_format

hide_window_decorations yes

background_opacity 0.72
background_blur 10

initial_window_width 110c
initial_window_height 30c


######### MacOS #########
# map cmd+p new_tab
# map alt+n previous_tab
# map alt+m next_tab
