#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper

exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 3 silent] obsidian
exec-once = [workspace 4 silent] Telegram
exec-once = [workspace 5 silent] nautilus
exec-once = [workspace 5 silent] kitty -e btop
exec-once = [workspace 5 silent] gnome-disks

##############################
### WINDOWS AND WORKSPACES ###
##############################

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-1

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*
windowrulev2 = float,class:^(org.gnome.Calendar)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(org.pulseaudio.pavucontrol)$

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
